// Mocks generated by Mockito 5.4.4 from annotations
// in youtube_music_app/test/services/download_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:collection' as _i6;

import 'package:http_parser/http_parser.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:youtube_explode_dart/src/channels/channels.dart' as _i4;
import 'package:youtube_explode_dart/src/playlists/playlist_client.dart' as _i3;
import 'package:youtube_explode_dart/src/reverse_engineering/models/fragment.dart'
    as _i13;
import 'package:youtube_explode_dart/src/search/search_client.dart' as _i5;
import 'package:youtube_explode_dart/src/videos/streams/mixins/hls_stream_info.dart'
    as _i11;
import 'package:youtube_explode_dart/src/videos/streams/streams.dart' as _i8;
import 'package:youtube_explode_dart/src/videos/video_client.dart' as _i2;
import 'package:youtube_explode_dart/src/videos/video_id.dart' as _i7;
import 'package:youtube_explode_dart/src/youtube_explode_base.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVideoClient_0 extends _i1.SmartFake implements _i2.VideoClient {
  _FakeVideoClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylistClient_1 extends _i1.SmartFake
    implements _i3.PlaylistClient {
  _FakePlaylistClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelClient_2 extends _i1.SmartFake implements _i4.ChannelClient {
  _FakeChannelClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchClient_3 extends _i1.SmartFake implements _i5.SearchClient {
  _FakeSearchClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnmodifiableListView_4<E> extends _i1.SmartFake
    implements _i6.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoId_5 extends _i1.SmartFake implements _i7.VideoId {
  _FakeVideoId_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_6 extends _i1.SmartFake implements Uri {
  _FakeUri_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamContainer_7 extends _i1.SmartFake
    implements _i8.StreamContainer {
  _FakeStreamContainer_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSize_8 extends _i1.SmartFake implements _i8.FileSize {
  _FakeFileSize_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBitrate_9 extends _i1.SmartFake implements _i8.Bitrate {
  _FakeBitrate_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoResolution_10 extends _i1.SmartFake
    implements _i8.VideoResolution {
  _FakeVideoResolution_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFramerate_11 extends _i1.SmartFake implements _i8.Framerate {
  _FakeFramerate_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaType_12 extends _i1.SmartFake implements _i9.MediaType {
  _FakeMediaType_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [YoutubeExplode].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeExplode extends _i1.Mock implements _i10.YoutubeExplode {
  MockYoutubeExplode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VideoClient get videos => (super.noSuchMethod(
        Invocation.getter(#videos),
        returnValue: _FakeVideoClient_0(
          this,
          Invocation.getter(#videos),
        ),
      ) as _i2.VideoClient);

  @override
  set videos(_i2.VideoClient? _videos) => super.noSuchMethod(
        Invocation.setter(
          #videos,
          _videos,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PlaylistClient get playlists => (super.noSuchMethod(
        Invocation.getter(#playlists),
        returnValue: _FakePlaylistClient_1(
          this,
          Invocation.getter(#playlists),
        ),
      ) as _i3.PlaylistClient);

  @override
  set playlists(_i3.PlaylistClient? _playlists) => super.noSuchMethod(
        Invocation.setter(
          #playlists,
          _playlists,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.ChannelClient get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: _FakeChannelClient_2(
          this,
          Invocation.getter(#channels),
        ),
      ) as _i4.ChannelClient);

  @override
  set channels(_i4.ChannelClient? _channels) => super.noSuchMethod(
        Invocation.setter(
          #channels,
          _channels,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.SearchClient get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _FakeSearchClient_3(
          this,
          Invocation.getter(#search),
        ),
      ) as _i5.SearchClient);

  @override
  set search(_i5.SearchClient? _search) => super.noSuchMethod(
        Invocation.setter(
          #search,
          _search,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StreamManifest].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamManifest extends _i1.Mock implements _i8.StreamManifest {
  MockStreamManifest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.UnmodifiableListView<_i8.StreamInfo> get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _FakeUnmodifiableListView_4<_i8.StreamInfo>(
          this,
          Invocation.getter(#streams),
        ),
      ) as _i6.UnmodifiableListView<_i8.StreamInfo>);

  @override
  _i6.UnmodifiableListView<_i8.AudioStreamInfo> get audio =>
      (super.noSuchMethod(
        Invocation.getter(#audio),
        returnValue: _FakeUnmodifiableListView_4<_i8.AudioStreamInfo>(
          this,
          Invocation.getter(#audio),
        ),
      ) as _i6.UnmodifiableListView<_i8.AudioStreamInfo>);

  @override
  _i6.UnmodifiableListView<_i8.VideoStreamInfo> get video =>
      (super.noSuchMethod(
        Invocation.getter(#video),
        returnValue: _FakeUnmodifiableListView_4<_i8.VideoStreamInfo>(
          this,
          Invocation.getter(#video),
        ),
      ) as _i6.UnmodifiableListView<_i8.VideoStreamInfo>);

  @override
  _i6.UnmodifiableListView<_i8.MuxedStreamInfo> get muxed =>
      (super.noSuchMethod(
        Invocation.getter(#muxed),
        returnValue: _FakeUnmodifiableListView_4<_i8.MuxedStreamInfo>(
          this,
          Invocation.getter(#muxed),
        ),
      ) as _i6.UnmodifiableListView<_i8.MuxedStreamInfo>);

  @override
  _i6.UnmodifiableListView<_i8.AudioOnlyStreamInfo> get audioOnly =>
      (super.noSuchMethod(
        Invocation.getter(#audioOnly),
        returnValue: _FakeUnmodifiableListView_4<_i8.AudioOnlyStreamInfo>(
          this,
          Invocation.getter(#audioOnly),
        ),
      ) as _i6.UnmodifiableListView<_i8.AudioOnlyStreamInfo>);

  @override
  _i6.UnmodifiableListView<_i8.VideoOnlyStreamInfo> get videoOnly =>
      (super.noSuchMethod(
        Invocation.getter(#videoOnly),
        returnValue: _FakeUnmodifiableListView_4<_i8.VideoOnlyStreamInfo>(
          this,
          Invocation.getter(#videoOnly),
        ),
      ) as _i6.UnmodifiableListView<_i8.VideoOnlyStreamInfo>);

  @override
  _i6.UnmodifiableListView<_i11.HlsStreamInfo> get hls => (super.noSuchMethod(
        Invocation.getter(#hls),
        returnValue: _FakeUnmodifiableListView_4<_i11.HlsStreamInfo>(
          this,
          Invocation.getter(#hls),
        ),
      ) as _i6.UnmodifiableListView<_i11.HlsStreamInfo>);
}

/// A class which mocks [MuxedStreamInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMuxedStreamInfo extends _i1.Mock implements _i8.MuxedStreamInfo {
  MockMuxedStreamInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.VideoId get videoId => (super.noSuchMethod(
        Invocation.getter(#videoId),
        returnValue: _FakeVideoId_5(
          this,
          Invocation.getter(#videoId),
        ),
      ) as _i7.VideoId);

  @override
  int get tag => (super.noSuchMethod(
        Invocation.getter(#tag),
        returnValue: 0,
      ) as int);

  @override
  Uri get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _FakeUri_6(
          this,
          Invocation.getter(#url),
        ),
      ) as Uri);

  @override
  _i8.StreamContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeStreamContainer_7(
          this,
          Invocation.getter(#container),
        ),
      ) as _i8.StreamContainer);

  @override
  _i8.FileSize get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeFileSize_8(
          this,
          Invocation.getter(#size),
        ),
      ) as _i8.FileSize);

  @override
  _i8.Bitrate get bitrate => (super.noSuchMethod(
        Invocation.getter(#bitrate),
        returnValue: _FakeBitrate_9(
          this,
          Invocation.getter(#bitrate),
        ),
      ) as _i8.Bitrate);

  @override
  String get audioCodec => (super.noSuchMethod(
        Invocation.getter(#audioCodec),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#audioCodec),
        ),
      ) as String);

  @override
  String get videoCodec => (super.noSuchMethod(
        Invocation.getter(#videoCodec),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#videoCodec),
        ),
      ) as String);

  @override
  _i8.VideoQuality get videoQuality => (super.noSuchMethod(
        Invocation.getter(#videoQuality),
        returnValue: _i8.VideoQuality.unknown,
      ) as _i8.VideoQuality);

  @override
  _i8.VideoResolution get videoResolution => (super.noSuchMethod(
        Invocation.getter(#videoResolution),
        returnValue: _FakeVideoResolution_10(
          this,
          Invocation.getter(#videoResolution),
        ),
      ) as _i8.VideoResolution);

  @override
  _i8.Framerate get framerate => (super.noSuchMethod(
        Invocation.getter(#framerate),
        returnValue: _FakeFramerate_11(
          this,
          Invocation.getter(#framerate),
        ),
      ) as _i8.Framerate);

  @override
  _i9.MediaType get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMediaType_12(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i9.MediaType);

  @override
  String get qualityLabel => (super.noSuchMethod(
        Invocation.getter(#qualityLabel),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#qualityLabel),
        ),
      ) as String);

  @override
  String get videoQualityLabel => (super.noSuchMethod(
        Invocation.getter(#videoQualityLabel),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#videoQualityLabel),
        ),
      ) as String);

  @override
  List<_i13.Fragment> get fragments => (super.noSuchMethod(
        Invocation.getter(#fragments),
        returnValue: <_i13.Fragment>[],
      ) as List<_i13.Fragment>);

  @override
  bool get isThrottled => (super.noSuchMethod(
        Invocation.getter(#isThrottled),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
