import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:youtube_music_app/services/youtube_service.dart';

import 'youtube_service_test.mocks.dart'; // Generated by mockito

@GenerateMocks([YoutubeExplode])
void main() {
  group('YoutubeService', () {
    late YoutubeService youtubeService;
    late MockYoutubeExplode mockYoutubeExplode;

    setUp(() {
      mockYoutubeExplode = MockYoutubeExplode();
      youtubeService = YoutubeService(youtubeExplode: mockYoutubeExplode);
    });

    test('searchVideos returns a list of videos on success', () async {
      // Arrange
      final query = 'test query';
      final mockVideo1 = Video(
        VideoId('id1'),
        'title1',
        'author1',
        'description1',
        Duration(seconds: 100),
        ThumbnailSet('id1'),
        DateTime.now(), // uploadDate
        Engagement(0, 0, 0, 0), // engagement - dummy data
        false, // isLive
        false, // isUpcoming
        ['keyword1', 'keyword2'], // keywords
        'en', // language
        true, // isFamilySafe
      );
      final mockVideo2 = Video(
        VideoId('id2'),
        'title2',
        'author2',
        'description2',
        Duration(seconds: 200),
        ThumbnailSet('id2'),
        DateTime.now(), // uploadDate
        Engagement(0, 0, 0, 0), // engagement - dummy data
        false, // isLive
        false, // isUpcoming
        ['keyword1', 'keyword2'], // keywords
        'en', // language
        true, // isFamilySafe
      );

      when(mockYoutubeExplode.search.search(query))
          .thenAnswer((_) async => VideoSearchList([mockVideo1, mockVideo2], null)); // Use VideoSearchList

      // Act
      final videos = await youtubeService.searchVideos(query);

      // Assert
      expect(videos, hasLength(2));
      expect(videos.first.title, 'title1');
      verify(mockYoutubeExplode.search.search(query)).called(1);
    });

    test('searchVideos returns an empty list for empty query', () async {
      // Arrange
      final query = '';

      // Act
      final videos = await youtubeService.searchVideos(query);

      // Assert
      expect(videos, isEmpty);
      verifyNever(mockYoutubeExplode.search.search(any as String));
    });

    test('searchVideos returns an empty list on error', () async {
      // Arrange
      final query = 'error query';
      when(mockYoutubeExplode.search.search(query))
          .thenThrow(Exception('Network error'));

      // Act
      final videos = await youtubeService.searchVideos(query);

      // Assert
      expect(videos, isEmpty);
      verify(mockYoutubeExplode.search.search(query)).called(1);
    });
  });
}
